auto_update: true
cache_folder: cache
collection_cache_file: collection.json
export_types:
  csv: true
  excel: true
location_field: 4
output_folder: output
pull_artist_sort_from_discogs:
  cache_file: artist_sort_cache.json
  enabled: true
  thorough: true
update_interval_hours: 24
